---
- stat: path=/tmp/activiti-{{ activiti_version }}.zip
  register: zip_archive

- name: Download activiti
  get_url:
    url: https://github.com/Activiti/Activiti/releases/download/activiti-{{ activiti_version }}/activiti-{{ activiti_version }}.zip
    dest: /tmp
    validate_certs: false
  when: (not zip_archive.stat.exists)

- name: Expand activiti zip
  unarchive:
    src=/tmp/activiti-{{ activiti_version }}.zip
    dest=/tmp
    copy=no

- name: Create target directory
  file: path=/tmp/WEB-INF/classes state=directory mode=0755

- name: create db.properties
  template:
    src=db.properties
    dest=/tmp/WEB-INF/classes/db.properties
    force=yes

- name: insert db.properties to activiti-explorer and rest api
  command:
    chdir=/tmp
    jar -uf activiti-{{ activiti_version }}/wars/activiti-{{ item }}.war WEB-INF/classes/db.properties
  with_items:
    - explorer
    - rest

# activiti-explorer creates test db and sample data at first time.
- name: create engine.properties for rest api (don't create test users)
  template:
    src=rest_engine.properties
    dest=/tmp/WEB-INF/classes/engine.properties
    force=yes

- name: insert engine.properties to rest api
  command:
    chdir=/tmp
    jar -uf activiti-{{ activiti_version }}/wars/activiti-rest.war WEB-INF/classes/engine.properties

- name: deploy activiti
  copy:
    src=/tmp/activiti-{{ activiti_version }}/wars/activiti-{{ item }}.war
    dest=/opt/tomcat/webapps/activiti-{{ item }}.war
    remote_src=True
  with_items:
    - explorer
    - rest

- name: wait activiti-explorer creates db and insert sample data.
- pause:
    minutes: 1

- name: stop tomcat
  service:
    name=tomcat
    state=stopped

- name: create engine.properties for activiti-explorer (don't create test users and sample reports)
  template:
    src=explorer_engine.properties
    dest=/tmp/WEB-INF/classes/engine.properties
    force=yes

- name: insert engine.properties to activiti-explorer
  command:
    chdir=/tmp
    jar -uf activiti-{{ activiti_version }}/wars/activiti-explorer.war WEB-INF/classes/engine.properties

- name: deploy activiti
  copy:
    src=/tmp/activiti-explorer/wars/activiti-{{ item }}.war
    dest=/opt/tomcat/webapps/activiti-explorer.war
    remote_src=True

- name: start tomcat
  service:
    name=tomcat
    state=started
