---
- name: Activiti
  hosts: activiti
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - ../ansible_common/common
    - { role: ../ansible_common/postgres, db_name: activiti, db_passwd: "{{ db_passwd_activiti }}" }
    - ../ansible_common/tomcat
    - { role: activiti, db_name: activiti, db_passwd: "{{ db_passwd_activiti }}" }
